image: maven:3.9.4-openjdk-23

build:
  stage: build
  script:
    - mvn compile


test:
  stage: test
  script:
    - mvn test -Dorg.apache.hc.client5.http.wire.level=WARN -Dorg.apache.hc.client5.http.wire.content.level=WARN
    - mvn clean test

